### ISSUE TITLE
experiment in real word

### ISSUE THREAD

**Issue by flyover-26** [VIS4ROB-lab/covins#12]
hi！
Could you tell me whether you tested covins in real world like ccm?how is its performance?
Looking forward to your reply!

**Comment by patriksc** [comment]
Yes, we have also run some real-world tests with COVINS. However, since there was no ground truth available in this setup, we do not have a quantitative performance evaluation available for those experiments.

**Comment by flyover-26** [comment]
thank you!
I test this in real-world on one computer.
And sometime  I suddenly got a problem like
------- selectserver: socket 11 hung up. -------
----> Exit Recv Thread
Comm 0: close
And orb-slam front-end stops immediately.

**Comment by patriksc** [comment]
I would imagine that you are probably losing WiFi connection between server and agent, which causes the communicator module on the agent to shut down.

**Comment by patriksc** [comment]
Problem seems resolved for the moment - closing this issue.

**Comment by South-River** [comment]
> thank you!
> I test this in real-world on one computer.
> And sometime  I suddenly got a problem like
> ------- selectserver: socket 11 hung up. -------
> ----> Exit Recv Thread
> Comm 0: close
> And orb-slam front-end stops immediately.

how's its performance in real world. Can you share me your results in real worlds.
Can it's results compete with the kimera multi or even better?
thank you:D
