### ISSUE TITLE
point in image

### ISSUE THREAD

**Issue by flyover-26** [VIS4ROB-lab/covins#14]
hi!
I notice in your viedo,we can see some green point on images.Can I see this by myself?
thank you!

**Comment by ThomasZiegler** [comment]
Hi
These green points are the default visualization from ORB SLAM 3. You should be able to activate the visualization using the following [config parameter](https://github.com/VIS4ROB-lab/covins/blob/c67e968667ee32a898d4feb237c276c25bda395f/covins_comm/config/config_comm.yaml#L30).
