### ISSUE TITLE
How to get the location information of different agents in the map？

### ISSUE THREAD

**Issue by zhouleiqiang** [VIS4ROB-lab/covins#18]
Hello, I ran two agents through the tutorial in your README, but only one pose topic (**/covins_markers_be**) is published in the terminal, I want to get the information of each agent in the global coordinate system, such as **/covins_markers_be_agent1** and **/ covins_markers_be_agent2**, is there any way to get it? Looking forward to your reply.

**Comment by patriksc** [comment]
Hello zhouleiqiang
Unfortunately, this functionality is currently not implemented in COVINS. To enable this, you would have to modify the visualization module of COVINS. Specifically, there is currently a single ROS publisher for all markers. You would have to extend this to multiple publishers for individual agents, and then use different publishers for data from different agents. 

However, while there is only one pose topic, the data associated to individual agents lives in individual namespaces: https://github.com/VIS4ROB-lab/covins/blob/c67e968667ee32a898d4feb237c276c25bda395f/covins_backend/src/covins_backend/visualization_be.cpp#L367 - maybe you can leverage this property for your purpose.

**Comment by zhouleiqiang** [comment]
> Hello zhouleiqiang Unfortunately, this functionality is currently not implemented in COVINS. To enable this, you would have to modify the visualization module of COVINS. Specifically, there is currently a single ROS publisher for all markers. You would have to extend this to multiple publishers for individual agents, and then use different publishers for data from different agents.
> 
> However, while there is only one pose topic, the data associated to individual agents lives in individual namespaces:
> 
> https://github.com/VIS4ROB-lab/covins/blob/c67e968667ee32a898d4feb237c276c25bda395f/covins_backend/src/covins_backend/visualization_be.cpp#L367
> 
> - maybe you can leverage this property for your purpose.



> Hello zhouleiqiang Unfortunately, this functionality is currently not implemented in COVINS. To enable this, you would have to modify the visualization module of COVINS. Specifically, there is currently a single ROS publisher for all markers. You would have to extend this to multiple publishers for individual agents, and then use different publishers for data from different agents.
> 
> However, while there is only one pose topic, the data associated to individual agents lives in individual namespaces:
> 
> https://github.com/VIS4ROB-lab/covins/blob/c67e968667ee32a898d4feb237c276c25bda395f/covins_backend/src/covins_backend/visualization_be.cpp#L367
> 
> - maybe you can leverage this property for your purpose.

Thanks for your answer, I think I know what to do

**Comment by patriksc** [comment]
Problem seems resolved for the moment - closing this issue.
