### ISSUE TITLE
Can I run covins on ROS2 foxy?

### ISSUE THREAD

**Issue by Jayan-K-Duggal** [VIS4ROB-lab/covins#24]
Can I run covins on ROS2 foxy?

**Comment by ThomasZiegler** [comment]
Hi, 

Unfortunately ROS2 is not supported by COVINS and it's also not planned in the near future. However, you can try using the [ros1_bridge](https://github.com/ros2/ros1_bridge). As disclaimer I myself do not have ROS2 and hence don't know if it works and also can't test it out. 

Feel free to add here any results you get in case you test it out. Could be interesting for other people as well. 

Regards Thomas
