### ISSUE TITLE
Unable to make covins_ Backend succeeded

### ISSUE THREAD

**Issue by cchester25** [VIS4ROB-lab/covins#35]
There are many "Undefined reference", when i make covins_backend , i dont know how to take it .
![2023-03-13 15-56-27 的屏幕截图](https://user-images.githubusercontent.com/70146927/224641016-25af1063-9be1-45ae-93d2-fad02f5c97e6.png)

**Comment by patriksc** [comment]
Hi, what environment are you using? Which command are you executing when this error occurs? I have just tested the deployment of COVINS on a 20.04 machine, I could deploy the code without running into error.

**Comment by chocho2222** [comment]
@patriksc First of all thank you for your work. I also encountered the same problem, I am using ubuntu18.04, when I run "./src/covins/install_file.sh 8", this error will appear, I will attach my screenshot below
![Screenshot from 2023-04-07 16-54-50](https://user-images.githubusercontent.com/91018212/230577830-7d3c2d2b-8a82-4ea5-a381-44aefcb8a7aa.png)

![Screenshot from 2023-04-07 16-57-33](https://user-images.githubusercontent.com/91018212/230578253-43e88226-fc93-4de6-9bca-1a2aae6adb10.png)
![Screenshot from 2023-04-07 16-58-08](https://user-images.githubusercontent.com/91018212/230578720-e34f0227-3a12-448d-8ad5-2b1b7ede9b8e.png)
![Screenshot from 2023-04-07 16-58-12](https://user-images.githubusercontent.com/91018212/230578753-b213fdee-9f73-4dfc-90d2-da6aeeb28089.png)

**Comment by chocho2222** [comment]
> There are many "Undefined reference", when i make covins_backend , i dont know how to take it . ![2023-03-13 15-56-27 的屏幕截图](https://user-images.githubusercontent.com/70146927/224641016-25af1063-9be1-45ae-93d2-fad02f5c97e6.png)
Hello bro,Is this problem solved?

**Comment by chocho2222** [comment]
@cchester25 
Bro, I solved this problem by modifying glog_catkin versio
![Screenshot from 2023-04-09 16-59-53](
![Screenshot from 2023-04-09 17-03-58](https://user-images.githubusercontent.com/91018212/230764334-30e58c0e-2714-4fd5-810a-53f4a34f7ed6.png)
https://user-images.githubusercontent.com/91018212/230764259-b5a8257b-4bd7-4950-a3f4-1b49910e3bf7.png)
n

**Comment by patriksc** [comment]
@chocho2222 Thanks a lot for sharing you experience and solution of the problem. Could you give some more details - which version of `glog` were you using, and what changes did you have to make to `glog_catkin`? I'll also try on a fresh 18.04 machine the next days, to see whether I can reproduce the error there.

**Comment by chocho2222** [comment]
@patriksc Sorry to get back to you, I posted a picture about the glog version above, but it didn't show up, the glog version I'm using is v0.50
![Screenshot from 2023-04-12 17-19-47](https://user-images.githubusercontent.com/91018212/231413644-f1a1257b-c9c5-4932-9455-48a4f2caadfd.png)

**Comment by patriksc** [comment]
Thanks for the additional information. I'll test in on a virtual machine with 18.04 then as well.

**Comment by patriksc** [comment]
Closing. Works on VM with 18.04.
