### ISSUE TITLE
Received full msgs for existing KF

### ISSUE THREAD

**Issue by swj6030829** [VIS4ROB-lab/covins#36]
![2023-03-17 16-47-15 的屏幕截图](https://user-images.githubusercontent.com/87260464/225856891-b78cecb3-28bf-4c99-85b0-584665fcf8ee.png)

**Comment by swj6030829** [comment]
Your work is very good, I use stereo in ORBSLAM3, it seems that the stereo mode is not supported, but I saw that you can only pass the keyframe of one camera, but I did not find out how to pass the keyframe of only one camera, Can you teach me how to do? Looking forward to your answer

**Comment by manthan99** [comment]
At present, COVINS doesn't support using a stereo/stereo-intertial front-end for ORB_SLAM3. If you are interested in using specifically a stereo-intertial front-end, I would suggest checking out the COVINS-G release for which it should be possible to use a stereo-inertial front-end with VINS-Fusion. You can have a look here:

https://github.com/manthan99/covins/tree/vins-covins

And this for the run instructions:

https://github.com/manthan99/covins/blob/vins-covins/docs/run_COVINS-G.md

I hope this helps.
