### ISSUE TITLE
How to save the output trajectory in ROS mode?

### ISSUE THREAD

**Issue by NatureLan-sudo** [VIS4ROB-lab/covins#37]
Hello, I'm sorry to bother you. I hope you can provide some help. Currently, in our code, we are able to output the trajectory and save it to the f_dataset-MH01_monoi.txt file when running in non-ROS mode. However, when we run the code using roslaunch, we are unable to output and save the corresponding trajectory. I have made some modifications to the code below, based on the non-ROS mode. However, I am encountering the following errors. Could you please provide some assistance?  @patriksc 
![image](https://user-images.githubusercontent.com/73154000/232656765-5516895d-fcdd-4d90-8044-9dae418a264b.png)
After the run is completed, I will use Ctrl+C to end the operation of the frontend and get the following result. I did not receive any trajectory files and the terminal appears to have thrown an error.
![image](https://user-images.githubusercontent.com/73154000/232658036-15a6c002-ef60-4889-bc7a-57852431a2e2.png)

**Comment by patriksc** [comment]
Hi! The message `terminate called without an active exception` usually appears when threads are not properly terminated. However, according to the terminal output, the trajectory files should have been written to disk. My best guess would be that the target file path to write the trajectory is incorrect. I would modify the code that writes the trajectory in [Systems.cc](https://github.com/VIS4ROB-lab/covins/blob/e21f25992369d39c9abb920259dd8fef3f30d973/orb_slam3/src/System.cc) to output the exact file path where it tries to write the trajectory file, and verify this path is correct and existing.
