### ISSUE TITLE
unable to detect loops

### ISSUE THREAD

**Issue by swj6030829** [VIS4ROB-lab/covins#39]
I would like to ask, I am using my own camera and the various proxies and backend are running smoothly. The local maps of each proxy can be generated successfully in the backend. However, it is still unable to detect loops regardless of how high the similarity of the scene is. May I know why or which parameters should I modify?

**Comment by swj6030829** [comment]
Hi, just to add, the framework I am using is COVINS-G.

**Comment by swj6030829** [comment]
![2023-04-27 20-28-20 的屏幕截图](https://user-images.githubusercontent.com/87260464/234862685-7ba7ea73-739a-4c96-ad7e-8106ab4e8186.png)
![2023-04-27 20-30-51 的屏幕截图](https://user-images.githubusercontent.com/87260464/234862713-f821bf56-f532-47d9-939c-00757a46ebc2.png)
Hello, this is my running result. I ran the first frontend and the second frontend separately on two ROSBAG datasets recorded in the same room with high scene similarity. I used the RGBD mode of ORBSLAM3 as my frontend, but I don't think this affects the data transmission to the backend. I published image frames and odometry information to the backend through ROS, and the backend can receive them, but it cannot detect any loop closures. Is it because there are too few keyframes generated, or some other reasons? I look forward to your reply.

**Comment by manthan99** [comment]
Hi

Are you using the Front-end ROS wrapper with RGBD ORBSLAM3? From the Rviz trajectories, they do not look good and seem to be very discontinuous (should be much smoother). 

Could you enable the Keyframe visualization in rviz and resend the screenshots ?

**Comment by swj6030829** [comment]
![2023-04-27 20-51-49 的屏幕截图](https://user-images.githubusercontent.com/87260464/234867738-730d2938-0aa9-4ba1-8976-dea0aa3929fe.png)
Hello, I am using the default settings and parameters. It seems that only from the third proxy node onwards, the keyframes can be seen in RVIZ. I have checked the dataset I recorded and found that the RGB publishing frequency is only 10 frames. I can adjust it to a higher frequency. Will this affect the detection of loop closures?

**Comment by manthan99** [comment]
Hi

It seems like you are indeed using the Front-end ROS Wrapper that we provide.

Unfortunately, this will not work with ORB-SLAM3 directly because of the local optimizations that ORB-SLAM3 does, the frame is always drifting (until initialized properly). If you wish to use ORB SLAM3 in RGBD mode, I suggest to do modifications to the ORB-SLAM3 codebase itself (Like it is done for the monocular case). 

You can have a look at this for reference: https://github.com/manthan99/covins_g#interfacing-a-custom-vio-system-with-covins

**Comment by patriksc** [comment]
Closing - inactive
