### ISSUE TITLE
An error occurred in the middle of the program

### ISSUE THREAD

**Issue by liming-jing** [VIS4ROB-lab/covins#4]
Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

+++++ KeyFrame Database Initialized +++++
selectserver: new connection from 192.168.31.31 on socket 11
Pass new ID 0 to client
Map 0 : 50 KFs | 1495 LMs
Map 0 : 100 KFs | 2287 LMs
Map 0 : 150 KFs | 2515 LMs
double free or corruption (out)
Aborted (core dumped)

When running the data set, the program was directly terminated, causing the front end to be unable to link to the server, and the map creation failed. How should I solve it?
In addition, when I used ros to play the program, it also appeared that the data set was not played, and the server terminated the program. What should I do?

**Comment by ThomasZiegler** [comment]
Hi
Can you also provide the logs from the agent? It looks like you only provided the server logs.

**Comment by ThomasZiegler** [comment]
When you use the ros wrapper you need to play the rosbag containing the data set in a separate terminal window.

**Comment by patriksc** [comment]
@liming-jing is this issue still relevant, or is the problem resolved in the meantime?

**Comment by patriksc** [comment]
closed - inactive
