### ISSUE TITLE
How to measure the network bandwidth utilization per second between the intelligent agent and the server ?

### ISSUE THREAD

**Issue by zwq-slamer** [VIS4ROB-lab/covins#46]
Hello! I am interested in your communication experiments and would like to know how you conducted them, as well as how you measured the network bandwidth utilization per second between the intelligent agent and the server. Could you please provide some detailed information and guidance? Thank you very much.

**Comment by manthan99** [comment]
Hi
For the results reported in COVINS-G, we measured the size of each message sent by the agent to the server. We  compute the total messages sent (Equivalent to # of Keyframes) for the dataset and then report the average data sent per second. 
Hope this helps. If not feel free to re-open the issue.
