### ISSUE TITLE
 How to change the slam3 version？

### ISSUE THREAD

**Issue by hyc-yuchen** [VIS4ROB-lab/covins#47]
How to change the slam3 version？

I need to use a version of slam3 that can run on a GPU, how can I change it?

**Comment by manthan99** [comment]
Hi 

I would recommend checking out these instructions in the readme for this:
[Interfacing a Custom VIO](https://github.com/VIS4ROB-lab/covins#interfacing-a-custom-vio-system-with-covins)

To quote from there, 

> For straightforward understanding which steps need to be taken to interface a VIO front-end with COVINS, we have defined the preprocessor macro COVINS_MOD in covins/covins_comm/include/covins/covins_base/typedefs_base.hpp. This macro indicates all modifications made to the original ORB-SLAM3 code in order to set up the communication with the server back-end.

So basically you can check our modified ORB_SLAM3 code for the macro COVINS_MOD and make similar changes to your ORB_SLAM3 version which supports GPU. 

I hope this helps
