### ISSUE TITLE
backend segmentfault

### ISSUE THREAD

**Issue by ggbond964** [VIS4ROB-lab/covins#49]
When I use a t265 camera to run the ORB_SLAM3 frontend,the covins beackend reports the segmentfault without any reasons.What might cause the segmentfault when using the t265 camera? 
The following are the frontend and backend logs when segmentfault happens.
frontend:
![图片](https://github.com/VIS4ROB-lab/covins/assets/144645705/79ffd354-ff05-4dae-9b47-b136772eea44)
backend:
![图片](https://github.com/VIS4ROB-lab/covins/assets/144645705/ab66648a-05cb-480f-ae27-c0c8e1e47adb)

**Comment by manthan99** [comment]
Hi

Could you please provide more details. Are you using the COVINS backend or COVINS-G backend ? 

Is your ORB-SLAM3 front-end initializing properly or failing ? The seg fault occurs in the back-end when the Front-end Map is not initialized properly or a Map-reset occurs

**Comment by patriksc** [comment]
Closing - inactive
