### ISSUE TITLE
Use my camera to transmit data

### ISSUE THREAD

**Issue by hyc-yuchen** [VIS4ROB-lab/covins#50]
How do I use my front-end camera /dev/video0 to pass data to the front-end and then view the composition information in the visualization window？

**Comment by manthan99** [comment]
Hi

What exactly do you mean by the composition information. I think that will depend on the front-end that you use.

Best
Manthan

**Comment by hyc-yuchen** [comment]
I use a webcam that transmits images through an rstp stream

> Hi
> 
> What exactly do you mean by the composition information. I think that will depend on the front-end that you use.
> 
> Best Manthan

**Comment by manthan99** [comment]
Hi

To answer shortly, you will need to publish the images and the IMU data on rostopics. This might be something that could be useful for the images: http://wiki.ros.org/video_stream_opencv. 

Note: The backend expects the inputs to be scaled metrically and hence you would either need an mono-IMU or a stereo setup for this. Not sure if you can just use a webcam for this.

If you are interested in monocular only, have a look at CCM SLAM repository (https://github.com/VIS4ROB-lab/ccm_slam)

Best
Manthan

**Comment by hyc-yuchen** [comment]
> Hi
> 
> To answer shortly, you will need to publish the images and the IMU data on rostopics. This might be something that could be useful for the images: http://wiki.ros.org/video_stream_opencv.
> 
> Note: The backend expects the inputs to be scaled metrically and hence you would either need an mono-IMU or a stereo setup for this. Not sure if you can just use a webcam for this.
> 
> If you are interested in monocular only, have a look at CCM SLAM repository (https://github.com/VIS4ROB-lab/ccm_slam)
> 
> Best Manthan

thank you for your replay

I imported the rstp stream into the virtual camera /dev/video0 and published it on rostopics using usb_cam. Now I constructed the related Mono file by modifying the camera in ros_mono.cc and used it to connect and communicate with the covins back-end. Although the front end can see the camera collecting data, but the back end does not receive relevant information, and rviz does not have relevant information. This means that it does not transmit data to the backend. It was constructed locally.


How can I fix it

**Comment by hyc-yuchen** [comment]
> Hi
> 
> To answer shortly, you will need to publish the images and the IMU data on rostopics. This might be something that could be useful for the images: http://wiki.ros.org/video_stream_opencv.
> 
> Note: The backend expects the inputs to be scaled metrically and hence you would either need an mono-IMU or a stereo setup for this. Not sure if you can just use a webcam for this.
> 
> If you are interested in monocular only, have a look at CCM SLAM repository (https://github.com/VIS4ROB-lab/ccm_slam)
> 
> Best Manthan

hello ，could teach me how to do it？

**Comment by manthan99** [comment]
Please check the CCM SLAM Repository  (https://github.com/VIS4ROB-lab/ccm_slam), where the detailed instructions are provided.
