### ISSUE TITLE
Invalid Image Dims: "- 1|-1”

### ISSUE THREAD

**Issue by chocho2222** [VIS4ROB-lab/covins#51]
I replaced ORB_SLAM3-V0.4 in Covins-G with V1.0, and then ran the RGB-D dataset (rgbd_dataset_freiburg3_walking_halfsphere). Every time I ran to 160-200 pictures, the error "Invalid Image Dims: "- 1|-1””, please tell me how to solve this error. Thank you very much!

          The following two pictures show errors when running to 177 and 194 pictures respectively.
![Screenshot from 2023-09-26 16-30-00](https://github.com/VIS4ROB-lab/covins/assets/91018212/b2ec7b1a-cc43-41b9-8481-e7b9e40b0c39)
![Screenshot from 2023-09-26 16-31-37](https://github.com/VIS4ROB-lab/covins/assets/91018212/10af59a2-0bbb-4c2b-80f9-019a9dadc996)

**Comment by chocho2222** [comment]
![Screenshot from 2023-09-27 18-53-37](https://github.com/VIS4ROB-lab/covins/assets/91018212/8bb4ae89-57ae-46ed-8a67-20bc06fd8ff5)

**Comment by chocho2222** [comment]
![Screenshot from 2023-09-27 18-55-13](https://github.com/VIS4ROB-lab/covins/assets/91018212/121da012-1218-486c-a745-3ec20bc97072)
And there is an error: "Segmentation fault (core dumped)"

**Comment by manthan99** [comment]
Hi

Just to clarify, the issue that you encounter is in the ORB-SLAM front-end, right  (Which cause the backend to crash)? 

Could you verify if the same sequence works correctly on the non-modified ORB-SLAM3 V1.0 repository ?

**Comment by chocho2222** [comment]
Sorry, I saw the news very late. I didn't deal with this problem for a month. Then I ran it again and it could run through the data set. But I recompiled ORB_SLAM3 and this problem appeared again. Next, I will follow your instructions. Comments to test run

**Comment by chocho2222** [comment]
> Hi
> 
> Just to clarify, the issue that you encounter is in the ORB-SLAM front-end, right (Which cause the backend to crash)?
> 
> Could you verify if the same sequence works correctly on the non-modified ORB-SLAM3 V1.0 repository ?
Sorry, I saw the news very late. I didn't deal with this problem for a month. Then I ran it again and it could run through the data set. But I recompiled ORB_SLAM3 and this problem appeared again. Next, I will follow your instructions. Comments to test run

**Comment by patriksc** [comment]
Closing - inactive
