### ISSUE TITLE
 "CovIns (G)" does not support pure monocular mode?

### ISSUE THREAD

**Issue by aax1n** [VIS4ROB-lab/covins#65]

**Comment by manthan99** [comment]
Hi

Unfortunately not, neither COVINS nor COVINS-G supports pure monocular mode. We only support front-ends which are able to give metrically scaled odometry outputs such as stereo, mono-inertial or stereo-inertial. You can have a look into [CCM SLAM](https://github.com/VIS4ROB-lab/ccm_slam) for monocular only Collaborative SLAM.
