### ISSUE TITLE
OpenVINS

### ISSUE THREAD

**Issue by htchr** [VIS4ROB-lab/covins#70]
Hello,

I noticed in the demo video for Covins-G that one of the agents is using an OpenVINS frontend, however, I have not been able to find any documentation or examples of other people using OpenVINS and Covins-G together.
OpenVINS is also mentioned in the paper, but no statistics or figures are given.
Could anyone please provide any guidance for using an OpenVINS frontend and a Covins-G backend? 

Thank you,

**Comment by manthan99** [comment]
Hi

We used OpenVINS with the ROS-based Front-end wrapper. The instructions for this would be similar to the instructions provided for SVO-pro (https://github.com/VIS4ROB-lab/covins/blob/master/docs/run_COVINS-G.md#run_fe_ros). Let me know if this makes it clear or you need further information.

Best
Manthan

**Comment by htchr** [comment]
Thank you
